DROP TABLE IF EXISTS STATS CASCADE;

CREATE TABLE IF NOT EXISTS STATS
(
    id        BIGINT                      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    app       VARCHAR                     NOT NULL,
    uri       VARCHAR                     NOT NULL,
    ip        VARCHAR                     NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_stat PRIMARY KEY (id)
);
